[package]
name = "blazecli"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
handlebars = "4.4.0"
regex = "1.10.2"
rust-embed = "8.0.0"
